const DEFAULT_PLAN={
Mo:{title:'Montag',split:'Arme · Schultern',groups:{Schulter:[['Seitheben',8.75,9],['Schulterpresse',12.5,12]],Arme:[['Push Down',41,10],['Kartana',27,9],['Bizeps Curls',36,4],['Hammer Curls',9,12]]}},
Di:{title:'Dienstag',split:'Off Day',groups:{}},
Mi:{title:'Mittwoch',split:'Rücken · Brust',groups:{Rücken:[['A-Bar',20,8],['1-armig Rudern links',45,9],['1-armig Rudern rechts',45,9],['Latzug',45,8],['Kreuzheben',null,null]],Brust:[['Butterflies',45,12],['Brustpresse',15,10],['Schrägbankdrücken',null,null],['Chest Press',15,8]]}},
Do:{title:'Donnerstag',split:'Beine · unterer Rücken',groups:{'Unterer Rücken':[['Kreuzheben',null,null]]}},
Fr:{title:'Freitag',split:'Arme · Schultern',groups:{Schulter:[['Seitheben',8.75,9],['Schulterpresse',12.5,12]],Arme:[['Push Down',41,10],['Kartana',27,9],['Bizeps Curls',36,4],['Hammer Curls',9,12]]}},
Sa:{title:'Samstag',split:'Off Day',groups:{}},
So:{title:'Sonntag',split:'Rücken · Brust',groups:{Rücken:[['A-Bar',20,8],['1-armig Rudern links',45,9],['1-armig Rudern rechts',45,9],['Latzug',45,8],['Kreuzheben',null,null]],Brust:[['Butterflies',45,12],['Brustpresse',15,10],['Schrägbankdrücken',null,null],['Chest Press',15,8]]}}
};
const ORDER=['Mo','Di','Mi','Do','Fr','Sa','So'];
const $=s=>document.querySelector(s),clean=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_'),fmt=n=>n==null?'—':String(n).replace('.',',');
const PLAN_KEY='gym:plan:v1',TASK_KEY=d=>'gym:tasks:'+d,WKEY=n=>'gym:v3:'+clean(n),COLLAPSE_KEY=(d,g)=>`gym:collapse:${d}:${g}`;
let selected=ORDER[(new Date().getDay()+6)%7],mode='training';
function clone(x){return JSON.parse(JSON.stringify(x))}
function loadPlan(){try{const p=JSON.parse(localStorage.getItem(PLAN_KEY)||'null');if(p)return p}catch{}const p=clone(DEFAULT_PLAN);localStorage.setItem(PLAN_KEY,JSON.stringify(p));return p}
let PLAN=loadPlan();
function savePlan(){localStorage.setItem(PLAN_KEY,JSON.stringify(PLAN))}
function state(n,w,r){try{let x=JSON.parse(localStorage.getItem(WKEY(n))||'null');if(x){x.note??='';return x}}catch{}const x={currentW:w,currentR:r,lastW:null,lastR:null,prW:w,prR:r,history:[],note:''};localStorage.setItem(WKEY(n),JSON.stringify(x));return x}
function num(v){v=v.trim().replace(',','.');if(!v)return null;v=Number(v);return Number.isFinite(v)&&v>=0?v:null}
function better(w,r,pw,pr){return w!=null&&r!=null&&(pw==null||w>pw||(w===pw&&(pr==null||r>pr)))}
function tasks(d){try{return JSON.parse(localStorage.getItem(TASK_KEY(d))||'[]')}catch{return[]}}
function saveTasks(d,x){localStorage.setItem(TASK_KEY(d),JSON.stringify(x))}
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function setup(){const css=`
.tabs{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin:0 0 10px}.tab{border:1px solid #24303d;background:#10141b;color:#8f9bad;border-radius:12px;padding:10px 4px;font-size:10px;font-weight:800}.tab.on{background:#198cff;border-color:#198cff;color:#fff}.hint{color:#748194;font-size:11px;margin:0 2px 14px}
.weekGrid{display:grid;gap:10px}.weekCard,.taskBox,.editorBox{background:linear-gradient(145deg,#121820,#0d1117);border:1px solid #222b37;border-radius:18px;padding:14px}.weekTop,.editorTop{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.weekTitle{font-size:17px;font-weight:800}.weekSub{font-size:11px;color:#69b5ff;font-weight:800;margin-top:3px}.muscleWrap{display:flex;gap:10px;align-items:center;margin-top:10px}.muscleSvg{width:92px;height:112px;flex:none}.muscleText{font-size:11px;line-height:1.45;color:#7f8a9b}.mini{display:flex;gap:5px;flex-wrap:wrap;margin-top:10px}.mini span{font-size:9px;color:#9ba6b5;background:#090d12;border:1px solid #252e39;border-radius:99px;padding:5px 7px}.small{border:1px solid #2a3441;background:#0a0e13;color:#fff;border-radius:10px;padding:9px 10px;font-size:11px;font-weight:800}.blue{border:0;background:#198cff;color:#fff;border-radius:10px;padding:10px 12px;font-weight:800}.danger{border:0;background:#25151b;color:#ff9aa4;border-radius:9px;padding:9px 10px;font-weight:800}
.taskRow{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center;padding:7px 0}.taskText,.editInput{width:100%;background:#090d12;border:1px solid #293440;color:#fff;border-radius:10px;padding:9px 10px}.del{border:0;background:#25151b;color:#ff9aa4;border-radius:9px;width:32px;height:32px;font-size:17px}.addRow{display:grid;grid-template-columns:1fr auto;gap:7px;margin-top:10px}.taskTools,.editTools{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}
.extra{margin-top:9px}.extra summary{list-style:none;color:#7faedc;font-size:11px;font-weight:800;cursor:pointer}.extra summary::-webkit-details-marker{display:none}.setRow{display:grid;grid-template-columns:38px 1fr 1fr;gap:7px;align-items:center;margin-top:7px}.setNo{font-size:10px;color:#7d8998;font-weight:800}.setRow .field{padding:7px 9px}.setRow input{font-size:18px}.note{width:100%;min-height:62px;margin-top:9px;background:#090d12;border:1px solid #293440;color:#fff;border-radius:11px;padding:9px 10px;resize:vertical;font:inherit;font-size:13px}.restMini{width:92px;height:112px;border:1px dashed #303947;border-radius:15px;display:grid;place-items:center;font-size:30px;background:#0a0e13}
.groupBlock{margin:12px 0}.groupToggle{width:100%;display:flex;align-items:center;justify-content:space-between;border:1px solid #222b37;background:#0d1218;color:#aeb9c8;border-radius:13px;padding:11px 12px;font-size:11px;font-weight:900;letter-spacing:1.2px;text-transform:uppercase}.groupToggle span:last-child{font-size:15px;color:#6f7d90}.groupContent{padding-top:2px}.groupContent.collapsed{display:none}
.editorGroup{border:1px solid #222b37;border-radius:15px;padding:12px;margin-top:10px}.editorGroupHead{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center}.editorExercise{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;margin-top:8px}.editorExercise small{display:block;color:#6f7c8e;margin-top:3px}.editLabel{font-size:9px;color:#718095;font-weight:800;margin:10px 0 4px}.editorAdd{display:grid;grid-template-columns:1fr auto;gap:7px;margin-top:9px}.empty{color:#7d8998;text-align:center;padding:18px 0}
@media(min-width:700px){.weekGrid{grid-template-columns:1fr 1fr}.tabs{gap:7px}.tab{font-size:11px}}
`;const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);const h=document.querySelector('header'),tabs=document.createElement('div');tabs.className='tabs';tabs.innerHTML='<button class="tab" data-mode="training">Training</button><button class="tab" data-mode="overview">Woche</button><button class="tab" data-mode="tasks">Aufgaben</button><button class="tab" data-mode="editor">Editor</button>';h.after(tabs);const hint=document.createElement('div');hint.id='hint';hint.className='hint';tabs.after(hint);const v=$('#view'),d=document.createElement('div');d.id='area';v.replaceWith(d);tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;render()})}
function muscle(parts={}){let f=k=>parts[k]?'#198cff':'#273241',l='#394555';return `<svg class="muscleSvg" viewBox="0 0 120 145"><rect width="120" height="145" rx="18" fill="#090d12" stroke="#202833"/><circle cx="37" cy="25" r="9" fill="#dce5f2"/><rect x="29" y="37" width="16" height="33" rx="8" fill="#dce5f2"/><ellipse cx="28" cy="41" rx="7" ry="6" fill="${f('shoulders')}" stroke="${l}"/><ellipse cx="46" cy="41" rx="7" ry="6" fill="${f('shoulders')}" stroke="${l}"/><rect x="20" y="42" width="9" height="26" rx="5" fill="${f('arms')}" stroke="${l}"/><rect x="45" y="42" width="9" height="26" rx="5" fill="${f('arms')}" stroke="${l}"/><rect x="31" y="46" width="12" height="12" rx="3" fill="${f('chest')}" stroke="${l}"/><rect x="31" y="59" width="12" height="10" rx="3" fill="${f('lowerback')}" stroke="${l}"/><rect x="30" y="72" width="6" height="31" rx="4" fill="${f('legs')}" stroke="${l}"/><rect x="38" y="72" width="6" height="31" rx="4" fill="${f('legs')}" stroke="${l}"/><circle cx="83" cy="25" r="9" fill="#dce5f2"/><rect x="75" y="37" width="16" height="33" rx="8" fill="#dce5f2"/><ellipse cx="74" cy="41" rx="7" ry="6" fill="${f('shoulders')}" stroke="${l}"/><ellipse cx="92" cy="41" rx="7" ry="6" fill="${f('shoulders')}" stroke="${l}"/><rect x="66" y="42" width="9" height="26" rx="5" fill="${f('arms')}" stroke="${l}"/><rect x="91" y="42" width="9" height="26" rx="5" fill="${f('arms')}" stroke="${l}"/><rect x="77" y="46" width="12" height="17" rx="3" fill="${f('back')}" stroke="${l}"/><rect x="77" y="64" width="12" height="7" rx="3" fill="${f('lowerback')}" stroke="${l}"/><rect x="76" y="72" width="6" height="31" rx="4" fill="${f('legs')}" stroke="${l}"/><rect x="84" y="72" width="6" height="31" rx="4" fill="${f('legs')}" stroke="${l}"/></svg>`}
function focus(d){const s=PLAN[d].split||'';if(s.includes('Arme'))return{arms:1,shoulders:1};if(s.includes('Rücken')&&s.includes('Brust'))return{back:1,chest:1};if(s.includes('Beine'))return{legs:1,lowerback:1};return{}}
function count(d){return Object.values(PLAN[d].groups||{}).reduce((a,x)=>a+x.length,0)}
function dayNav(){return `<nav id="days" class="days">${ORDER.map(d=>`<button class="day ${d===selected?'active':''}" data-day="${d}">${d}</button>`).join('')}</nav>`}
function bindDays(){document.querySelectorAll('#days button').forEach(b=>b.onclick=()=>{selected=b.dataset.day;render()})}
function isCollapsed(d,g){return localStorage.getItem(COLLAPSE_KEY(d,g))==='1'}
function setCollapsed(d,g,v){localStorage.setItem(COLLAPSE_KEY(d,g),v?'1':'0')}
function training(){const p=PLAN[selected],groups=Object.entries(p.groups||{});let out=dayNav()+`<div class="dayHeader"><h2>${p.title}</h2><div class="split">${p.split}</div></div>`;$('#saveBtn').style.display='block';$('#historyBtn').style.display='inline-flex';$('#saveBtn').disabled=!groups.length;$('#saveBtn').style.opacity=groups.length?'1':'.45';if(!groups.length)return out+'<div class="rest"><strong>Rest Day</strong>Regeneration · Mobilität · Schlaf</div>';for(const[g,list]of groups){const collapsed=isCollapsed(selected,g);out+=`<section class="groupBlock"><button class="groupToggle" data-group="${esc(g)}"><span>${esc(g)}</span><span>${collapsed?'＋':'−'}</span></button><div class="groupContent ${collapsed?'collapsed':''}">`;for(const[n,w,r]of list){const x=state(n,w,r),id=clean(selected+n);out+=`<article class="card"><div class="exerciseTop"><div class="name">${esc(n)}</div><span class="prTag">PR ${fmt(x.prW)} kg × ${fmt(x.prR)}</span></div><div class="stats"><span class="stat">Aktuell <strong>${fmt(x.currentW)} kg × ${fmt(x.currentR)}</strong></span><span class="stat">Letztes <strong>${fmt(x.lastW)} kg × ${fmt(x.lastR)}</strong></span></div><div class="inputs"><div class="field"><label>SATZ 1 · KG</label><input id="${id}s1w" inputmode="decimal" placeholder="leer"></div><div class="field"><label>SATZ 1 · WDH.</label><input id="${id}s1r" inputmode="numeric" placeholder="leer"></div></div><details class="extra"><summary>＋ Sätze & Notiz</summary><div class="setRow"><span class="setNo">Satz 2</span><div class="field"><input id="${id}s2w" inputmode="decimal" placeholder="kg"></div><div class="field"><input id="${id}s2r" inputmode="numeric" placeholder="Wdh."></div></div><div class="setRow"><span class="setNo">Satz 3</span><div class="field"><input id="${id}s3w" inputmode="decimal" placeholder="kg"></div><div class="field"><input id="${id}s3r" inputmode="numeric" placeholder="Wdh."></div></div><textarea id="${id}note" class="note" placeholder="Notiz zur Übung …">${esc(x.note)}</textarea></details></article>`}out+='</div></section>'}return out}
function overview(){$('#saveBtn').style.display='none';$('#historyBtn').style.display='inline-flex';let out='<div class="dayHeader"><h2>Wochenübersicht</h2><div class="split">Muskel-Fokus & Trainingstage</div></div><div class="weekGrid">';for(const d of ORDER){const p=PLAN[d],rest=!Object.keys(p.groups||{}).length,tc=tasks(d).length;out+=`<section class="weekCard"><div class="weekTop"><div><div class="weekTitle">${p.title}</div><div class="weekSub">${esc(p.split)}</div></div><button class="small openDay" data-day="${d}">Öffnen</button></div><div class="muscleWrap">${rest?'<div class="restMini">🛌</div>':muscle(focus(d))}<div class="muscleText">${rest?'Erholung, Schlaf und lockere Bewegung.':'Blau markiert sind die Muskelbereiche, die an diesem Tag im Fokus stehen.'}</div></div><div class="mini"><span>${count(d)} Übungen</span><span>${tc} Aufgabe${tc===1?'':'n'}</span></div></section>`}return out+'</div>'}
function taskView(){$('#saveBtn').style.display='none';$('#historyBtn').style.display='none';const p=PLAN[selected],ts=tasks(selected),rows=ts.length?ts.map((t,i)=>`<div class="taskRow" data-i="${i}"><input class="ck" type="checkbox" ${t.done?'checked':''}><input class="taskText ${t.done?'done':''}" value="${esc(t.text)}"><button class="del">×</button></div>`).join(''):'<div class="empty">Noch keine Aufgaben.</div>';return dayNav()+`<div class="dayHeader"><h2>${p.title}</h2><div class="split">Aufgaben separat verwalten</div></div><section class="taskBox"><div class="muscleText">Dieser Bereich ist getrennt vom Training, damit beim täglichen Eintragen nichts stört.</div><div id="taskList">${rows}</div><div class="addRow"><input id="newTask" class="taskText" placeholder="Neue Aufgabe"><button id="addTask" class="blue">＋</button></div><div class="taskTools"><button id="clearDone" class="small">Erledigte löschen</button><button id="clearAll" class="small">Alle löschen</button></div></section>`}
function editorView(){$('#saveBtn').style.display='none';$('#historyBtn').style.display='none';const p=PLAN[selected];let out=dayNav()+`<div class="dayHeader"><h2>${p.title}</h2><div class="split">Trainingsplan bearbeiten</div></div><section class="editorBox"><div class="muscleText">Hier kannst du bestehende Kategorien und Übungen umbenennen, Übungen löschen oder neue hinzufügen. Deine bisherigen Trainingswerte werden beim Umbenennen mit übernommen.</div>`;const groups=Object.entries(p.groups||{});if(!groups.length)out+='<div class="empty">Noch keine Kategorien an diesem Tag.</div>';for(const[g,list]of groups){out+=`<div class="editorGroup" data-group="${esc(g)}"><div class="editLabel">KATEGORIE</div><div class="editorGroupHead"><input class="editInput groupName" value="${esc(g)}"><button class="danger removeGroup">Löschen</button></div>`;for(let i=0;i<list.length;i++){const[n,w,r]=list[i];out+=`<div class="editorExercise" data-index="${i}"><div><input class="editInput exerciseName" value="${esc(n)}"><small>${fmt(w)} kg · ${fmt(r)} Wdh. als Startwert</small></div><button class="danger removeExercise">×</button></div>`}out+=`<div class="editorAdd"><input class="editInput newExercise" placeholder="Neue Übung"><button class="blue addExercise">＋</button></div></div>`}out+=`<div class="editLabel">NEUE KATEGORIE</div><div class="editorAdd"><input id="newGroup" class="editInput" placeholder="z. B. Bauch"><button id="addGroup" class="blue">＋</button></div><div class="editTools"><button id="resetPlan" class="small">Standardplan wiederherstellen</button></div></section>`;return out}
function render(){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('on',b.dataset.mode===mode));$('#hint').textContent=mode==='training'?'Kategorien kannst du antippen und ein- oder ausklappen.':mode==='overview'?'Der ganze Wochenplan auf einen Blick.':mode==='tasks'?'Aufgaben pro Tag hinzufügen, bearbeiten oder löschen.':'Bestehende Übungen und Kategorien direkt bearbeiten.';$('#area').innerHTML=mode==='training'?training():mode==='overview'?overview():mode==='tasks'?taskView():editorView();bindDays();bindModeActions()}
function bindModeActions(){document.querySelectorAll('.openDay').forEach(b=>b.onclick=()=>{selected=b.dataset.day;mode='training';render()});document.querySelectorAll('.groupToggle').forEach(b=>b.onclick=()=>{const g=b.dataset.group,next=!isCollapsed(selected,g);setCollapsed(selected,g,next);const content=b.nextElementSibling;if(content)content.classList.toggle('collapsed',next);const mark=b.lastElementChild;if(mark)mark.textContent=next?'＋':'−'});if(mode==='tasks')bindTasks();if(mode==='editor')bindEditor()}
function bindTasks(){const add=$('#addTask'),input=$('#newTask');if(add)add.onclick=()=>{const t=input.value.trim();if(!t)return toast('Bitte Aufgabe eingeben');const x=tasks(selected);x.push({text:t,done:false});saveTasks(selected,x);render();toast('Aufgabe hinzugefügt')};document.querySelectorAll('.taskRow').forEach(r=>{const i=+r.dataset.i,ck=r.querySelector('.ck'),txt=r.querySelector('.taskText'),del=r.querySelector('.del');ck.onchange=()=>{const x=tasks(selected);x[i].done=ck.checked;saveTasks(selected,x);render()};txt.onblur=()=>{const x=tasks(selected);x[i].text=txt.value.trim();saveTasks(selected,x)};del.onclick=()=>{const x=tasks(selected);x.splice(i,1);saveTasks(selected,x);render()}});$('#clearDone').onclick=()=>{saveTasks(selected,tasks(selected).filter(x=>!x.done));render()};$('#clearAll').onclick=()=>{saveTasks(selected,[]);render()}}
function sameExercise(a,b){return String(a||'').trim().toLocaleLowerCase('de-DE')===String(b||'').trim().toLocaleLowerCase('de-DE')}
function dayHasExercise(day,name,exceptGroup=null,exceptIndex=-1){for(const[g,list]of Object.entries(PLAN[day]?.groups||{}))for(let i=0;i<list.length;i++){if(g===exceptGroup&&i===exceptIndex)continue;if(sameExercise(list[i][0],name))return true}return false}
function exerciseUsedAnywhere(name){for(const p of Object.values(PLAN))for(const list of Object.values(p.groups||{}))for(const[n]of list)if(sameExercise(n,name))return true;return false}
function migrateExercise(oldName,newName){if(oldName===newName)return;const oldKey=WKEY(oldName),newKey=WKEY(newName),old=localStorage.getItem(oldKey),exists=localStorage.getItem(newKey);if(old&&!exists)localStorage.setItem(newKey,old);if(old&&!exerciseUsedAnywhere(oldName))localStorage.removeItem(oldKey)}
function bindEditor(){document.querySelectorAll('.editorGroup').forEach(box=>{const oldGroup=box.dataset.group,groupInput=box.querySelector('.groupName');groupInput.onchange=()=>{const newGroup=groupInput.value.trim();if(!newGroup||newGroup===oldGroup)return render();if(PLAN[selected].groups[newGroup]){groupInput.value=oldGroup;return toast('Kategorie existiert bereits')}PLAN[selected].groups[newGroup]=PLAN[selected].groups[oldGroup];delete PLAN[selected].groups[oldGroup];savePlan();render();toast('Kategorie umbenannt')};box.querySelector('.removeGroup').onclick=()=>{delete PLAN[selected].groups[oldGroup];savePlan();render();toast('Kategorie gelöscht – Trainingshistorie bleibt erhalten')};box.querySelectorAll('.editorExercise').forEach(row=>{const i=+row.dataset.index,oldName=PLAN[selected].groups[oldGroup][i][0],input=row.querySelector('.exerciseName');input.onchange=()=>{const n=input.value.trim();if(!n||n===oldName)return render();if(dayHasExercise(selected,n,oldGroup,i)){input.value=oldName;return toast('Diese Übung gibt es an diesem Tag bereits')}PLAN[selected].groups[oldGroup][i][0]=n;migrateExercise(oldName,n);savePlan();render();toast('Übung umbenannt')};row.querySelector('.removeExercise').onclick=()=>{PLAN[selected].groups[oldGroup].splice(i,1);savePlan();render();toast('Übung entfernt – Trainingshistorie bleibt erhalten')}});box.querySelector('.addExercise').onclick=()=>{const input=box.querySelector('.newExercise'),n=input.value.trim();if(!n)return toast('Bitte Übungsname eingeben');if(dayHasExercise(selected,n))return toast('Diese Übung gibt es an diesem Tag bereits');PLAN[selected].groups[oldGroup].push([n,null,null]);savePlan();render();toast('Übung hinzugefügt')}});$('#addGroup').onclick=()=>{const n=$('#newGroup').value.trim();if(!n)return toast('Bitte Kategorienamen eingeben');if(PLAN[selected].groups[n])return toast('Kategorie existiert bereits');PLAN[selected].groups[n]=[];savePlan();render();toast('Kategorie hinzugefügt')};$('#resetPlan').onclick=()=>{PLAN=clone(DEFAULT_PLAN);savePlan();render();toast('Standardplan wiederhergestellt – Trainingshistorie bleibt erhalten')}}
function saveWorkout(){const p=PLAN[selected];let saved=0,prs=0;for(const list of Object.values(p.groups||{}))for(const[n,iw,ir]of list){const id=clean(selected+n),s1w=$('#'+id+'s1w'),s1r=$('#'+id+'s1r');if(!s1w||!s1r)continue;const vals=[];for(let s=1;s<=3;s++){const we=$('#'+id+`s${s}w`),re=$('#'+id+`s${s}r`),w=we?num(we.value):null,r=re?num(re.value):null;if(w!=null||r!=null)vals.push([w,r])}const note=$('#'+id+'note');const x=state(n,iw,ir);if(note)x.note=note.value;if(!vals.length){localStorage.setItem(WKEY(n),JSON.stringify(x));continue}let[nw,nr]=vals[0];nw=nw==null?x.currentW:nw;nr=nr==null?x.currentR:nr;if(nw==null||nr==null){toast('Bei neuen Übungen zuerst Gewicht und Wdh. eintragen');continue}const resolvedSets=vals.map(([vw,vr])=>[vw==null?nw:vw,vr==null?nr:vr]);x.lastW=x.currentW;x.lastR=x.currentR;x.currentW=nw;x.currentR=nr;let isPR=false;for(const[aw,ar]of resolvedSets){if(better(aw,ar,x.prW,x.prR)){x.prW=aw;x.prR=ar;isPR=true}}if(isPR)prs++;x.history.unshift({date:new Date().toISOString(),w:nw,r:nr,sets:resolvedSets,pr:isPR});x.history=x.history.slice(0,250);localStorage.setItem(WKEY(n),JSON.stringify(x));saved++}render();toast(saved?`${saved} gespeichert${prs?` · ${prs} neuer PR 🏆`:''}`:'Keine neuen Werte')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>e.classList.remove('show'),2200)}
function showHistory(){const rows=[];const seen=new Set;for(const p of Object.values(PLAN))for(const list of Object.values(p.groups||{}))for(const[n,w,r]of list){if(seen.has(n))continue;seen.add(n);const x=state(n,w,r);for(const h of x.history||[])rows.push({name:n,...h})}rows.sort((a,b)=>new Date(b.date)-new Date(a.date));$('#historyContent').innerHTML=rows.length?rows.slice(0,100).map(h=>`<div class="historyItem"><b>${esc(h.name)}${h.pr?' 🏆':''}</b><small>${new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(h.date))} · ${fmt(h.w)} kg × ${fmt(h.r)}</small></div>`).join(''):'<div class="empty">Noch kein Training gespeichert.</div>';$('#history').showModal()}
setup();$('#saveBtn').onclick=saveWorkout;$('#historyBtn').onclick=showHistory;$('#closeHistory').onclick=()=>$('#history').close();render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));