const SUPABASE_URL='https://bifulnoewabqfzpfivzz.supabase.co';
const SUPABASE_KEY='sb_publishable_UdQU5Ze3fj4zZksEOD4ikw_CjZYoOt4';
const SESSION_KEY='gym-auth-session';
const LAST_USER_KEY='gym_last_cloud_user';
const DIRTY_KEY='gym_cloud_dirty';
let cloudSession=null,suppressCloudSync=false,syncTimer=null,appLoaded=false,remoteVersion=0,syncChain=Promise.resolve(),localGeneration=0;

const rawSetItem=Storage.prototype.setItem;
const rawRemoveItem=Storage.prototype.removeItem;
Storage.prototype.setItem=function(key,value){rawSetItem.call(this,key,value);if(this===localStorage&&String(key).startsWith('gym:')&&!suppressCloudSync){localGeneration++;rawSetItem.call(localStorage,DIRTY_KEY,'1');scheduleCloudSync()}};
Storage.prototype.removeItem=function(key){rawRemoveItem.call(this,key);if(this===localStorage&&String(key).startsWith('gym:')&&!suppressCloudSync){localGeneration++;rawSetItem.call(localStorage,DIRTY_KEY,'1');scheduleCloudSync()}};

function loadSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function saveSession(s){cloudSession=s;if(s)rawSetItem.call(localStorage,SESSION_KEY,JSON.stringify(s));else rawRemoveItem.call(localStorage,SESSION_KEY)}
function authHeaders(extra={}){return{apikey:SUPABASE_KEY,Authorization:`Bearer ${cloudSession?.access_token||''}`,...extra}}
function authErrorMessage(data,fallback='Anmeldung fehlgeschlagen'){const m=(data?.msg||data?.message||data?.error_description||data?.error||'').toString();if(/invalid login credentials/i.test(m))return'E-Mail oder Passwort ist falsch.';if(/email not confirmed/i.test(m))return'Bitte bestätige zuerst deine E-Mail.';if(/user already registered/i.test(m))return'Für diese E-Mail existiert bereits ein Konto.';if(/password/i.test(m)&&/6/i.test(m))return'Das Passwort muss mindestens 6 Zeichen haben.';return m||fallback}

async function authRequest(path,options={}){const r=await fetch(SUPABASE_URL+path,{...options,headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json',...(options.headers||{})}});let data=null;try{data=await r.json()}catch{}return{ok:r.ok,status:r.status,data}}
async function refreshSession(){if(!cloudSession?.refresh_token)return false;try{const res=await authRequest('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:cloudSession.refresh_token})});if(!res.ok||!res.data?.access_token){if([400,401,403].includes(res.status))saveSession(null);return false}saveSession({...cloudSession,...res.data,user:res.data.user||cloudSession.user,expires_at_ms:Date.now()+(res.data.expires_in||3600)*1000});return true}catch{return false}}
async function api(path,options={},retry=true){if(cloudSession?.expires_at_ms&&cloudSession.expires_at_ms<Date.now()+60000)await refreshSession();let r=await fetch(SUPABASE_URL+path,{...options,headers:authHeaders(options.headers||{})});if(r.status===401&&retry&&await refreshSession())return api(path,options,false);return r}

function gymSnapshot(){const storage={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('gym:'))storage[k]=localStorage.getItem(k)}return{schemaVersion:2,storage}}
function clearGymStorage(){const keys=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('gym:'))keys.push(k)}keys.forEach(k=>rawRemoveItem.call(localStorage,k))}
function applySnapshot(state){const storage=state?.storage&&typeof state.storage==='object'?state.storage:{};suppressCloudSync=true;try{clearGymStorage();for(const[k,v]of Object.entries(storage))rawSetItem.call(localStorage,k,String(v))}finally{suppressCloudSync=false}}
function hasSnapshotData(state){return !!state?.storage&&Object.keys(state.storage).length>0}
function parseJson(v,fallback=null){try{return JSON.parse(v)}catch{return fallback}}
function safetyKeys(prefix,uid){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith(prefix+uid+'_'))out.push(k)}return out.sort().reverse()}
function pruneSafetyBackups(prefix,uid,keep=6){for(const k of safetyKeys(prefix,uid).slice(keep))try{rawRemoveItem.call(localStorage,k)}catch{}}
function saveSafetyState(state,label='auto',prefix='gym_local_safety_'){const uid=cloudSession?.user?.id||localStorage.getItem(LAST_USER_KEY)||'unknown',key=`${prefix}${uid}_${Date.now()}_${label}`,payload=JSON.stringify(state);pruneSafetyBackups(prefix,uid,6);try{rawSetItem.call(localStorage,key,payload)}catch{pruneSafetyBackups(prefix,uid,2);try{rawSetItem.call(localStorage,key,payload)}catch{return null}}pruneSafetyBackups(prefix,uid,6);return key}
function saveLocalSafetyBackup(label='auto'){return saveSafetyState(gymSnapshot(),label,'gym_local_safety_')}
function saveRemoteSafetyBackup(state,label='conflict'){return state?saveSafetyState(state,label,'gym_remote_safety_'):null}
function historyKey(h){return [h?.date??'',h?.w??'',h?.r??'',JSON.stringify(h?.sets??[])].join('|')}
function pairValue(w,r){if(w==null||r==null)return null;const nw=Number(w),nr=Number(r);return Number.isFinite(nw)&&Number.isFinite(nr)?{w:nw,r:nr}:null}
function pairBetter(a,b){a=pairValue(a?.w,a?.r);b=pairValue(b?.w,b?.r);if(!a)return b;if(!b)return a;return a.w>b.w||(a.w===b.w&&a.r>b.r)?a:b}
function mergeWorkoutState(remoteRaw,localRaw){const r=parseJson(remoteRaw,{})||{},l=parseJson(localRaw,{})||{},map=new Map();for(const h of [...(Array.isArray(r.history)?r.history:[]),...(Array.isArray(l.history)?l.history:[])])map.set(historyKey(h),h);const history=[...map.values()].sort((a,b)=>new Date(b?.date||0)-new Date(a?.date||0)).slice(0,250);const latest=history[0]||null,previous=history[1]||null;let best=null;for(const p of [{w:r.prW,r:r.prR},{w:l.prW,r:l.prR}])best=pairBetter(p,best);for(const h of history){best=pairBetter(pairValue(h?.w,h?.r),best);for(const set of h?.sets||[])best=pairBetter(pairValue(set?.[0]??h?.w,set?.[1]??h?.r),best)}const currentW=latest?.w??l.currentW??r.currentW??null,currentR=latest?.r??l.currentR??r.currentR??null;return JSON.stringify({...r,...l,currentW,currentR,lastW:previous?.w??l.lastW??r.lastW??null,lastR:previous?.r??l.lastR??r.lastR??null,prW:Number.isFinite(best?.w)?best.w:(l.prW??r.prW??null),prR:Number.isFinite(best?.r)?best.r:(l.prR??r.prR??null),history,note:(l.note??'')!==''?l.note:(r.note??'')})}
function mergePlan(remoteRaw,localRaw){const r=parseJson(remoteRaw,null),l=parseJson(localRaw,null);if(!r)return localRaw;if(!l)return remoteRaw;const out=JSON.parse(JSON.stringify(r));for(const[day,ld]of Object.entries(l)){const rd=out[day]||{};out[day]={...rd,...ld,groups:{...(rd.groups||{})}};for(const[g,ll]of Object.entries(ld.groups||{})){const rl=Array.isArray(rd.groups?.[g])?rd.groups[g]:[],merged=rl.map(x=>Array.isArray(x)?[...x]:x);for(const item of Array.isArray(ll)?ll:[]){const name=String(item?.[0]??'').trim().toLocaleLowerCase('de-DE'),i=merged.findIndex(x=>String(x?.[0]??'').trim().toLocaleLowerCase('de-DE')===name);if(i>=0)merged[i]=item;else merged.push(item)}out[day].groups[g]=merged}}return JSON.stringify(out)}
function mergeTasks(remoteRaw,localRaw){const r=parseJson(remoteRaw,[]),l=parseJson(localRaw,[]);if(!Array.isArray(r))return localRaw;if(!Array.isArray(l))return remoteRaw;const m=new Map();for(const t of [...r,...l]){const text=String(t?.text??'').trim(),k=text.toLocaleLowerCase('de-DE');if(!k)continue;const prev=m.get(k);m.set(k,{text:prev?.text||text,done:!!(prev?.done||t?.done)})}return JSON.stringify([...m.values()])}
function mergeSnapshots(remoteState,localState){const r=remoteState?.storage&&typeof remoteState.storage==='object'?remoteState.storage:{},l=localState?.storage&&typeof localState.storage==='object'?localState.storage:{},storage={...r};for(const[k,v]of Object.entries(l)){if(!(k in r)){storage[k]=v;continue}if(v===r[k]){storage[k]=v;continue}if(k.startsWith('gym:v3:'))storage[k]=mergeWorkoutState(r[k],v);else if(k==='gym:plan:v1')storage[k]=mergePlan(r[k],v);else if(k.startsWith('gym:tasks:'))storage[k]=mergeTasks(r[k],v);else storage[k]=v}return{schemaVersion:Math.max(Number(remoteState?.schemaVersion||0),Number(localState?.schemaVersion||0),2),storage}}

async function getRemoteState(){const uid=cloudSession?.user?.id;if(!uid)return null;const r=await api(`/rest/v1/app_state?select=state,version,updated_at&user_id=eq.${encodeURIComponent(uid)}&limit=1`);if(!r.ok)throw new Error('Cloud-Daten konnten nicht geladen werden');const rows=await r.json();return rows[0]||null}
async function rpc(name,body={}){const r=await api(`/rest/v1/rpc/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let data=null;try{data=await r.json()}catch{}if(!r.ok){const e=new Error(data?.message||data?.hint||data?.details||name);e.status=r.status;e.data=data;throw e}return data}
async function doPushRemoteState(){const uid=cloudSession?.user?.id;if(!uid)return;let snapshot=gymSnapshot(),generation=localGeneration;saveLocalSafetyBackup('before_sync');for(let attempt=0;attempt<3;attempt++){try{const version=await rpc('save_app_state',{p_state:snapshot,p_expected_version:remoteVersion});remoteVersion=Number(version)||remoteVersion+1;if(localGeneration===generation){rawSetItem.call(localStorage,DIRTY_KEY,'0')}else{rawSetItem.call(localStorage,DIRTY_KEY,'1');setTimeout(()=>scheduleCloudSync(),80)}showCloudStatus(true);return remoteVersion}catch(err){const conflict=/state_conflict/i.test(JSON.stringify(err.data||{})+err.message);if(!conflict){showCloudStatus(false);throw err}const remote=await getRemoteState();if(!remote){remoteVersion=0;continue}saveRemoteSafetyBackup(remote.state,'state_conflict');remoteVersion=Number(remote.version)||0;const latestLocal=gymSnapshot();generation=localGeneration;snapshot=mergeSnapshots(remote.state,latestLocal);applySnapshot(snapshot);rawSetItem.call(localStorage,DIRTY_KEY,'1')}}showCloudStatus(false);const e=new Error('state_conflict_unresolved');e.code='state_conflict_unresolved';throw e}
function pushRemoteState(){syncChain=syncChain.catch(()=>{}).then(()=>doPushRemoteState());return syncChain}
function scheduleCloudSync(){if(!cloudSession?.user?.id)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>pushRemoteState().catch(()=>showCloudStatus(false)),700)}
function showCloudStatus(ok=true){const btn=document.querySelector('#cloudAccount');if(!btn)return;btn.dataset.sync=ok?'ok':'error';btn.style.outline=ok?'':'2px solid #ff6572';btn.title=ok?(cloudSession?.user?.email||'Profil'):'Synchronisierung fehlgeschlagen – lokale Sicherung vorhanden'}

async function hydrateUser(){const uid=cloudSession?.user?.id;if(!uid)throw new Error('Keine Benutzer-ID');const previousUser=localStorage.getItem(LAST_USER_KEY);let local=gymSnapshot();if(previousUser&&previousUser!==uid&&hasSnapshotData(local)){saveLocalSafetyBackup('user_switch');suppressCloudSync=true;try{clearGymStorage();rawSetItem.call(localStorage,DIRTY_KEY,'0')}finally{suppressCloudSync=false}local=gymSnapshot()}const remote=await getRemoteState(),dirty=localStorage.getItem(DIRTY_KEY)==='1';if(remote&&hasSnapshotData(remote.state)){remoteVersion=Number(remote.version)||1;if(dirty&&hasSnapshotData(local)&&(!previousUser||previousUser===uid)){saveLocalSafetyBackup('startup_unsynced');await pushRemoteState()}else{applySnapshot(remote.state);rawSetItem.call(localStorage,DIRTY_KEY,'0')}}else if(hasSnapshotData(local)&&(!previousUser||previousUser===uid)){remoteVersion=0;await pushRemoteState()}else{remoteVersion=0;rawSetItem.call(localStorage,DIRTY_KEY,'0')}suppressCloudSync=true;rawSetItem.call(localStorage,LAST_USER_KEY,uid);suppressCloudSync=false}

function injectAuthStyles(){const s=document.createElement('style');s.textContent=`
#authGate{position:fixed;inset:0;z-index:9999;background:radial-gradient(circle at 50% -10%,#172336 0,#080a0e 38%);display:grid;place-items:center;padding:22px;color:#f7f9fc;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",sans-serif}
.authCard{width:min(420px,100%);background:linear-gradient(145deg,#121820,#0d1117);border:1px solid #222b37;border-radius:24px;padding:22px;box-shadow:0 24px 80px rgba(0,0,0,.35)}.authBrand{display:flex;gap:12px;align-items:center;margin-bottom:20px}.authBrand img{width:50px;height:50px;border-radius:13px}.authBrand h1{font-size:27px;margin:0;letter-spacing:-.8px}.authBrand p{font-size:11px;color:#7f8a9b;margin:4px 0 0}.authTabs{display:grid;grid-template-columns:1fr 1fr;background:#090d12;border:1px solid #222b37;border-radius:12px;padding:4px;margin-bottom:15px}.authTab{border:0;background:transparent;color:#788497;border-radius:9px;padding:9px;font-weight:800}.authTab.on{background:#198cff;color:#fff}.authField{margin-top:10px}.authField label{display:block;font-size:9px;color:#788497;font-weight:900;letter-spacing:.6px;margin:0 0 5px 2px}.authField input{width:100%;border:1px solid #293440;border-radius:12px;background:#090d12;color:#fff;padding:13px 12px;font:inherit;font-size:16px;outline:none}.authField input:focus{border-color:#198cff;box-shadow:0 0 0 2px rgba(25,140,255,.1)}#authSubmit{width:100%;border:0;border-radius:13px;background:#198cff;color:#fff;padding:13px;margin-top:14px;font-weight:900}.authMsg{min-height:18px;margin-top:11px;color:#8d9aab;font-size:11px;line-height:1.4}.authMsg.error{color:#ff9aa4}.authInfo{text-align:center;color:#657184;font-size:10px;margin-top:14px}.cloudActions{display:flex;gap:7px;align-items:center}
`;document.head.appendChild(s)}
function renderAuth(mode='login',message='',isError=false){let gate=document.querySelector('#authGate');if(!gate){gate=document.createElement('div');gate.id='authGate';document.body.appendChild(gate)}gate.dataset.mode=mode;gate.innerHTML=`<div class="authCard"><div class="authBrand"><img src="icons/icon.svg" alt=""><div><h1>Trainingsplaner</h1><p>by Paiblo · Deine Trainingsdaten auf jedem Gerät.</p></div></div><div class="authTabs"><button class="authTab ${mode==='login'?'on':''}" data-auth="login">Anmelden</button><button class="authTab ${mode==='signup'?'on':''}" data-auth="signup">Registrieren</button></div><form id="authForm"><div class="authField"><label>E-MAIL</label><input id="authEmail" type="email" autocomplete="email" required placeholder="name@beispiel.de"></div><div class="authField"><label>PASSWORT</label><input id="authPassword" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" minlength="6" required placeholder="Mindestens 6 Zeichen"></div><button id="authSubmit" type="submit">${mode==='login'?'Anmelden':'Konto erstellen'}</button></form><div class="authMsg ${isError?'error':''}">${message}</div><div class="authInfo">Trainingsdaten werden deinem Benutzerkonto zugeordnet und nicht öffentlich in GitHub gespeichert.</div></div>`;gate.querySelectorAll('.authTab').forEach(b=>b.onclick=()=>renderAuth(b.dataset.auth));gate.querySelector('#authForm').onsubmit=e=>handleAuthSubmit(e,mode)}
async function handleAuthSubmit(e,mode){e.preventDefault();const email=document.querySelector('#authEmail').value.trim(),password=document.querySelector('#authPassword').value;const btn=document.querySelector('#authSubmit');btn.disabled=true;btn.textContent='Bitte warten …';try{if(mode==='login'){const res=await authRequest('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});if(!res.ok||!res.data?.access_token)throw new Error(authErrorMessage(res.data));saveSession({...res.data,expires_at_ms:Date.now()+(res.data.expires_in||3600)*1000});await enterApp()}else{const res=await authRequest('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password})});if(!res.ok)throw new Error(authErrorMessage(res.data,'Registrierung fehlgeschlagen'));if(res.data?.access_token){saveSession({...res.data,expires_at_ms:Date.now()+(res.data.expires_in||3600)*1000});await enterApp()}else renderAuth('login','Konto erstellt. Bitte bestätige die E-Mail und melde dich danach an.')}}catch(err){renderAuth(mode,err.message||'Es ist ein Fehler aufgetreten.',true)}}

async function validateStoredSession(){cloudSession=loadSession();if(!cloudSession?.access_token)return false;if(!navigator.onLine)return !!cloudSession?.user?.id;if(cloudSession.expires_at_ms&&cloudSession.expires_at_ms<Date.now()+60000){const ok=await refreshSession();if(!ok)return !!cloudSession?.user?.id&&!navigator.onLine}try{const r=await api('/auth/v1/user');if(r.status===401||r.status===403)return false;if(!r.ok)return !!cloudSession?.user?.id;const user=await r.json();cloudSession.user=user;saveSession(cloudSession);return true}catch{return !!cloudSession?.user?.id}}
function loadMainApp(){if(appLoaded)return;appLoaded=true;document.querySelector('#authGate')?.remove();const script=document.createElement('script');script.src='app.js';script.onload=()=>{injectAccountButton();const social=document.createElement('script');social.src='social.js';social.onerror=()=>showCloudStatus(false);document.body.appendChild(social)};script.onerror=()=>{appLoaded=false;renderAuth('login','Die App konnte nicht geladen werden. Bitte neu versuchen.',true)};document.body.appendChild(script)}
function injectAccountButton(){const header=document.querySelector('header'),history=document.querySelector('#historyBtn');if(!header||!history)return;let wrap=document.createElement('div');wrap.className='cloudActions';header.insertBefore(wrap,history);wrap.appendChild(history);const b=document.createElement('button');b.id='cloudAccount';b.className='iconBtn';b.type='button';b.textContent='P';b.title=cloudSession?.user?.email||'Profil';b.setAttribute('aria-label','Profil');b.onclick=()=>window.openSocialProfile?window.openSocialProfile():void 0;wrap.appendChild(b)}
async function enterApp(){try{await hydrateUser();loadMainApp()}catch(err){renderAuth('login','Cloud-Verbindung fehlgeschlagen. Deine lokalen Daten wurden nicht gelöscht. Bitte versuche es erneut.',true)}}
async function logout(){saveLocalSafetyBackup('before_logout');try{await pushRemoteState()}catch{alert('Abmelden wurde gestoppt, weil die Cloud-Sicherung nicht bestätigt werden konnte. Deine lokalen Daten bleiben erhalten.');return}saveSession(null);suppressCloudSync=true;try{clearGymStorage()}finally{suppressCloudSync=false}location.reload()}

async function bootCloud(){injectAuthStyles();renderAuth('login','Anmeldung wird geprüft …');try{if(await validateStoredSession()){await enterApp();return}if(navigator.onLine)saveSession(null);renderAuth('login')}catch{const stored=loadSession();if(stored?.user?.id){cloudSession=stored;await enterApp()}else renderAuth('login','Cloud ist gerade nicht erreichbar. Bitte versuche es erneut.',true)}}
bootCloud();
