let weightFeaturePatched=false;
function weightEsc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function fmtWeight(v){if(v==null||v==='')return'—';return Number(v).toLocaleString('de-DE',{minimumFractionDigits:1,maximumFractionDigits:2})+' kg'}
function fmtWeightDate(v){try{return new Intl.DateTimeFormat('de-DE',{dateStyle:'medium'}).format(new Date(v))}catch{return''}}
const WEIGHT_OUTBOX_PREFIX='gym:outbox:weight:';
function queueWeightRow(row){if(row?.client_entry_id)localStorage.setItem(WEIGHT_OUTBOX_PREFIX+row.client_entry_id,JSON.stringify(row))}
function removeWeightRow(id){if(id)localStorage.removeItem(WEIGHT_OUTBOX_PREFIX+id)}
function pendingWeightRows(uid){const rows=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k?.startsWith(WEIGHT_OUTBOX_PREFIX))continue;try{const row=JSON.parse(localStorage.getItem(k)||'null');if(row?.user_id===uid)rows.push(row)}catch{}}return rows}
async function sendWeightRow(row){const r=await api('/rest/v1/weight_entries?on_conflict=user_id,client_entry_id',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify(row)});if(!r.ok)throw new Error('weight_'+r.status);removeWeightRow(row.client_entry_id);return true}
async function saveWeightEntry(value,measuredAt=new Date().toISOString()){const uid=cloudSession?.user?.id;if(!uid)throw new Error('Keine Sitzung');const clientId=(crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`),row={user_id:uid,client_entry_id:clientId,weight_kg:Number(Number(value).toFixed(2)),measured_at:measuredAt};queueWeightRow(row);try{await sendWeightRow(row);return{synced:true,row}}catch{return{synced:false,row}}}
async function flushWeightOutbox(){const uid=cloudSession?.user?.id;if(!uid||!navigator.onLine)return;for(const row of pendingWeightRows(uid)){try{await sendWeightRow(row)}catch{break}}}
async function getWeightEntries(uid=cloudSession?.user?.id,limit=12){if(!uid)return[];let remote=[];try{const r=await api(`/rest/v1/weight_entries?select=id,user_id,client_entry_id,weight_kg,measured_at,created_at&user_id=eq.${encodeURIComponent(uid)}&order=measured_at.desc&limit=${Math.max(1,Math.min(50,limit))}`);if(r.ok)remote=await r.json()}catch{}const pending=uid===cloudSession?.user?.id?pendingWeightRows(uid):[],map=new Map();for(const row of [...pending,...remote])map.set(row.client_entry_id||row.id,row);return [...map.values()].sort((a,b)=>new Date(b.measured_at)-new Date(a.measured_at)).slice(0,Math.max(1,Math.min(50,limit)))}
window.saveWeightEntry=saveWeightEntry;window.flushWeightOutbox=flushWeightOutbox;
function weightSummary(rows=[]){const latest=rows[0]||null,previous=rows[1]||null;const delta=latest&&previous?Number(latest.weight_kg)-Number(previous.weight_kg):null;return{latest,previous,delta,count:rows.length}}
function weightDeltaText(delta){if(delta==null||Math.abs(delta)<0.005)return delta==null?'Noch kein Vergleich':'±0 kg zur letzten Messung';const sign=delta>0?'+':'';return `${sign}${Number(delta).toLocaleString('de-DE',{minimumFractionDigits:1,maximumFractionDigits:2})} kg zur letzten Messung`}
function weightOwnMarkup(rows=[]){const s=weightSummary(rows);const history=rows.length?rows.slice(0,10).map(x=>`<div class="weightHistoryRow"><span>${fmtWeightDate(x.measured_at)}</span><b>${fmtWeight(x.weight_kg)}</b></div>`).join(''):'<div class="socialMsg">Noch keine Gewichtsmessung gespeichert.</div>';return `<div id="weightOwnCard" class="rankBox weightCard"><div class="weightTop"><div><div class="weightTitle">Körpergewicht</div><div class="weightCurrent">${s.latest?fmtWeight(s.latest.weight_kg):'Noch kein Wert'}</div><div class="tiny">${s.latest?weightDeltaText(s.delta):'Deine Einträge sind für angenommene Freunde sichtbar.'}</div></div><span class="weightIcon">⚖️</span></div><div class="weightAdd"><input id="weightInput" class="socialInput" inputmode="decimal" type="text" placeholder="z. B. 82,4 kg"><button id="weightSave" class="socialBtn">Speichern</button></div><div id="weightMsg" class="socialMsg"></div><details class="weightDetails"><summary>Gewichtsverlauf (${rows.length})</summary>${history}</details></div>`}
function weightCompareMarkup(ownRows=[],friendRows=[],friendName='Freund'){const a=weightSummary(ownRows),b=weightSummary(friendRows);return `<div id="weightCompareCard" class="rankBox weightCard"><div class="weightTitle">Gewicht</div><div class="compareGrid weightCompareGrid"><div class="compareCol"><h3>Du</h3><div class="weightCompareValue">${a.latest?fmtWeight(a.latest.weight_kg):'—'}</div><div class="tiny">${a.latest?weightDeltaText(a.delta):'Kein Wert'}</div></div><div class="compareCol"><h3>${weightEsc(friendName)}</h3><div class="weightCompareValue">${b.latest?fmtWeight(b.latest.weight_kg):'—'}</div><div class="tiny">${b.latest?weightDeltaText(b.delta):'Kein Wert'}</div></div></div>${friendRows.length?`<details class="weightDetails"><summary>Verlauf von ${weightEsc(friendName)}</summary>${friendRows.slice(0,8).map(x=>`<div class="weightHistoryRow"><span>${fmtWeightDate(x.measured_at)}</span><b>${fmtWeight(x.weight_kg)}</b></div>`).join('')}</details>`:''}</div>`}
function injectWeightStyles(){if(document.querySelector('#weightStyles'))return;const s=document.createElement('style');s.id='weightStyles';s.textContent=`.weightCard{margin-top:12px}.weightTop{display:flex;justify-content:space-between;align-items:center;gap:10px}.weightTitle{font-size:11px;color:#7f8a9b;font-weight:900;text-transform:uppercase;letter-spacing:.7px}.weightCurrent{font-size:25px;font-weight:900;margin-top:3px}.weightIcon{font-size:26px}.weightAdd{display:grid;grid-template-columns:1fr auto;gap:7px;margin-top:12px}.weightDetails{margin-top:10px}.weightDetails summary{cursor:pointer;color:#8bb7e2;font-size:10px;font-weight:800;list-style:none}.weightDetails summary::-webkit-details-marker{display:none}.weightHistoryRow{display:flex;justify-content:space-between;gap:12px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.05);font-size:11px;color:#8793a3}.weightHistoryRow:last-child{border-bottom:0}.weightHistoryRow b{color:#fff}.weightCompareValue{font-size:20px;font-weight:900;margin:3px 0}.weightCompareGrid{margin-top:9px}`;document.head.appendChild(s)}
async function injectOwnWeight(){const section=document.querySelector('#s_profile');if(!section||document.querySelector('#weightOwnCard'))return;injectWeightStyles();let rows=[];try{rows=await getWeightEntries(cloudSession.user.id,30)}catch{}const target=section.querySelector('.statGrid')||section.firstElementChild;target?.insertAdjacentHTML('afterend',weightOwnMarkup(rows));const save=document.querySelector('#weightSave'),input=document.querySelector('#weightInput'),msg=document.querySelector('#weightMsg');if(save)save.onclick=async()=>{const raw=(input.value||'').trim().replace(',','.');const value=Number(raw);if(!Number.isFinite(value)||value<20||value>400){msg.textContent='Bitte ein gültiges Gewicht zwischen 20 und 400 kg eingeben.';return}const normalized=Number(value.toFixed(2));if(!confirm(`${fmtWeight(normalized)} als neuen Gewichtswert speichern?`))return;save.disabled=true;save.textContent='Speichert …';msg.textContent='';try{const result=await saveWeightEntry(normalized);msg.textContent=result.synced?'Gewicht sicher gespeichert.':'Gewicht lokal vorgemerkt und wird automatisch synchronisiert.';input.value='';document.querySelector('#weightOwnCard')?.remove();await injectOwnWeight()}catch(e){msg.textContent='Gewicht konnte nicht vorgemerkt werden. Bitte erneut versuchen.';save.disabled=false;save.textContent='Speichern'}}}
async function injectFriendWeight(uid,name){const area=document.querySelector('#compareArea');if(!area)return;document.querySelector('#weightCompareCard')?.remove();injectWeightStyles();try{const [ownRows,friendRows]=await Promise.all([getWeightEntries(cloudSession.user.id,12),getWeightEntries(uid,12)]);area.insertAdjacentHTML('beforeend',weightCompareMarkup(ownRows,friendRows,name))}catch{area.insertAdjacentHTML('beforeend','<div id="weightCompareCard" class="rankBox"><div class="socialMsg">Gewicht ist nur für bestätigte Freunde sichtbar oder konnte gerade nicht geladen werden.</div></div>')}}
function patchWeightFeature(){if(weightFeaturePatched||typeof window.openSocialProfile!=='function')return false;weightFeaturePatched=true;injectWeightStyles();const originalOpen=window.openSocialProfile;window.openSocialProfile=async function(tab='profile'){const result=await originalOpen(tab);setTimeout(()=>injectOwnWeight(),0);return result};if(typeof window.compareWith==='function'){const originalCompare=window.compareWith;window.compareWith=async function(uid,name){const result=await originalCompare(uid,name);await injectFriendWeight(uid,name);return result}}return true}
(function waitForSocial(n=0){if(patchWeightFeature())return;if(n<200)setTimeout(()=>waitForSocial(n+1),100)})();window.addEventListener('online',()=>flushWeightOutbox().catch(()=>{}));setTimeout(()=>flushWeightOutbox().catch(()=>{}),1200);